name: tp1
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - arpack=3.7.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - curl=8.2.1
  - expat=2.5.0
  - gdbm=1.18
  - gettext=0.21.1
  - git=2.38.1
  - gmp=6.2.1
  - icu=73.2
  - julia=1.8.1
  - keyutils=1.6.1
  - krb5=1.20.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgit2=1.5.0
  - libgomp=13.2.0
  - libhwloc=2.9.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.24
  - libopenblas-ilp64=0.3.24
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mbedtls=3.3.0
  - metis=5.1.0
  - mpfr=4.2.0
  - ncurses=6.4
  - openblas-ilp64=0.3.24
  - openlibm=0.8.1
  - openssl=3.1.3
  - p7zip=16.02
  - pcre2=10.37
  - perl=5.34.0
  - readline=8.2
  - suitesparse=5.10.1
  - tbb=2021.8.0
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
